In [ ]:
# How to merge multiple csv files into one datafram and save to a csv file

In [41]:
import os
import glob
import pandas as pd
import csv
import pathlib

In [42]:
pwd

'/Users/johngore/Desktop/USC/Homework/tableau_hw/Resources/Data/Winter'

In [43]:
ls

citibike-tripdata-201901.csv  citibike-tripdata-201912.csv
citibike-tripdata-201902.csv

In [44]:
os.chdir("/Users/johngore/Desktop/USC/Homework/tableau_hw/Resources/Data/Winter")

In [45]:
pwd

'/Users/johngore/Desktop/USC/Homework/tableau_hw/Resources/Data/Winter'

In [46]:
ls

citibike-tripdata-201901.csv  citibike-tripdata-201912.csv
citibike-tripdata-201902.csv

In [47]:
file_extension = ".csv"

In [48]:
all_filenames = [i for i in glob.glob(f"*{file_extension}")]

In [49]:
print(all_filenames)

['citibike-tripdata-201902.csv', 'citibike-tripdata-201901.csv', 'citibike-tripdata-201912.csv']

In [50]:
all_filenames = [i for i in glob.glob(f"*{file_extension}")]
all_data = (pd.read_csv(f, sep=',') for f in all_filenames)
merged_data = pd.concat(all_data, ignore_index=True)

In [51]:
combined_data = pd.DataFrame(merged_data)

In [52]:
combined_data.tail(10)

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
2866231,1789,2019-12-31 23:54:54.5700,2020-01-01 00:24:43.9070,3306.0,10 St & 7 Ave,40.666208,-73.981999,3416.0,7 Ave & Park Pl,40.677615,-73.973243,40692,Subscriber,1983,1
2866232,193,2019-12-31 23:54:55.6090,2019-12-31 23:58:09.5930,437.0,Macon St & Nostrand Ave,40.680983,-73.950048,344.0,Monroe St & Bedford Ave,40.685144,-73.953809,18317,Subscriber,1967,1
2866233,1775,2019-12-31 23:55:21.1960,2020-01-01 00:24:56.6520,3306.0,10 St & 7 Ave,40.666208,-73.981999,3416.0,7 Ave & Park Pl,40.677615,-73.973243,35047,Customer,1981,2
2866234,122099,2019-12-31 23:55:30.7260,2020-01-02 09:50:30.6710,3712.0,W 35 St & Dyer Ave,40.754692,-73.997402,347.0,Greenwich St & W Houston St,40.728846,-74.008591,38866,Customer,1977,1
2866235,1838,2019-12-31 23:57:04.6040,2020-01-01 00:27:43.3920,3711.0,E 13 St & Avenue A,40.729667,-73.980680,515.0,W 43 St & 10 Ave,40.760094,-73.994618,41688,Subscriber,1965,1
2866236,93,2019-12-31 23:58:18.0160,2019-12-31 23:59:51.6360,3141.0,1 Ave & E 68 St,40.765005,-73.958185,3142.0,1 Ave & E 62 St,40.761227,-73.960940,28734,Subscriber,1985,2
2866237,786,2019-12-31 23:58:59.8960,2020-01-01 00:12:06.3460,490.0,8 Ave & W 33 St,40.751551,-73.993934,513.0,W 56 St & 10 Ave,40.768254,-73.988639,41418,Subscriber,1991,1
2866238,351,2019-12-31 23:59:03.6950,2020-01-01 00:04:54.8730,3349.0,Grand Army Plaza & Plaza St West,40.672968,-73.970880,3368.0,5 Ave & 3 St,40.672816,-73.983524,27746,Subscriber,1935,2
2866239,1571,2019-12-31 23:59:21.3610,2020-01-01 00:25:32.9420,252.0,MacDougal St & Washington Sq,40.732264,-73.998522,366.0,Clinton Ave & Myrtle Ave,40.693261,-73.968896,28506,Subscriber,1980,1
2866240,310,2019-12-31 23:59:55.2960,2020-01-01 00:05:05.7270,3351.0,E 102 St & 1 Ave,40.786995,-73.941648,3379.0,E 103 St & Lexington Ave,40.790305,-73.947558,21013,Subscriber,1969,0

In [53]:
combined_data.describe()

,tripduration,start station id,start station latitude,start station longitude,end station id,end station latitude,end station longitude,bikeid,birth year,gender
count,2.866241e+06,2.866214e+06,2.866241e+06,2.866241e+06,2.866214e+06,2.866241e+06,2.866241e+06,2.866241e+06,2.866241e+06,2.866241e+06
mean,8.036963e+02,1.633885e+03,4.073746e+01,-7.398196e+01,1.620060e+03,4.073727e+01,-7.398224e+01,3.026706e+04,1.979170e+03,1.176227e+00
std,8.635128e+03,1.468312e+03,3.010828e-02,1.876734e-02,1.466771e+03,2.982357e-02,1.882458e-02,7.123838e+03,1.233303e+01,4.764864e-01
min,6.100000e+01,7.200000e+01,4.065540e+01,-7.401713e+01,7.200000e+01,4.065540e+01,-7.406391e+01,1.452900e+04,1.885000e+03,0.000000e+00
25%,3.150000e+02,3.830000e+02,4.071882e+01,-7.399456e+01,3.800000e+02,4.071882e+01,-7.399468e+01,2.694700e+04,1.969000e+03,1.000000e+00
50%,5.150000e+02,5.080000e+02,4.073913e+01,-7.398484e+01,5.070000e+02,4.073827e+01,-7.398546e+01,3.164600e+04,1.982000e+03,1.000000e+00
75%,8.680000e+02,3.288000e+03,4.075715e+01,-7.397283e+01,3.285000e+03,4.075660e+01,-7.397344e+01,3.497700e+04,1.989000e+03,1.000000e+00
max,3.304262e+06,3.911000e+03,4.086600e+01,-7.388100e+01,3.911000e+03,4.086600e+01,-7.388100e+01,4.204600e+04,2.003000e+03,2.000000e+00

In [54]:
combined_data['gender'] = combined_data['gender'].replace([0, 1, 2],['Undisclosed','Male','Female'])

In [55]:
combined_data.tail(10)

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
2866231,1789,2019-12-31 23:54:54.5700,2020-01-01 00:24:43.9070,3306.0,10 St & 7 Ave,40.666208,-73.981999,3416.0,7 Ave & Park Pl,40.677615,-73.973243,40692,Subscriber,1983,Male
2866232,193,2019-12-31 23:54:55.6090,2019-12-31 23:58:09.5930,437.0,Macon St & Nostrand Ave,40.680983,-73.950048,344.0,Monroe St & Bedford Ave,40.685144,-73.953809,18317,Subscriber,1967,Male
2866233,1775,2019-12-31 23:55:21.1960,2020-01-01 00:24:56.6520,3306.0,10 St & 7 Ave,40.666208,-73.981999,3416.0,7 Ave & Park Pl,40.677615,-73.973243,35047,Customer,1981,Female
2866234,122099,2019-12-31 23:55:30.7260,2020-01-02 09:50:30.6710,3712.0,W 35 St & Dyer Ave,40.754692,-73.997402,347.0,Greenwich St & W Houston St,40.728846,-74.008591,38866,Customer,1977,Male
2866235,1838,2019-12-31 23:57:04.6040,2020-01-01 00:27:43.3920,3711.0,E 13 St & Avenue A,40.729667,-73.980680,515.0,W 43 St & 10 Ave,40.760094,-73.994618,41688,Subscriber,1965,Male
2866236,93,2019-12-31 23:58:18.0160,2019-12-31 23:59:51.6360,3141.0,1 Ave & E 68 St,40.765005,-73.958185,3142.0,1 Ave & E 62 St,40.761227,-73.960940,28734,Subscriber,1985,Female
2866237,786,2019-12-31 23:58:59.8960,2020-01-01 00:12:06.3460,490.0,8 Ave & W 33 St,40.751551,-73.993934,513.0,W 56 St & 10 Ave,40.768254,-73.988639,41418,Subscriber,1991,Male
2866238,351,2019-12-31 23:59:03.6950,2020-01-01 00:04:54.8730,3349.0,Grand Army Plaza & Plaza St West,40.672968,-73.970880,3368.0,5 Ave & 3 St,40.672816,-73.983524,27746,Subscriber,1935,Female
2866239,1571,2019-12-31 23:59:21.3610,2020-01-01 00:25:32.9420,252.0,MacDougal St & Washington Sq,40.732264,-73.998522,366.0,Clinton Ave & Myrtle Ave,40.693261,-73.968896,28506,Subscriber,1980,Male
2866240,310,2019-12-31 23:59:55.2960,2020-01-01 00:05:05.7270,3351.0,E 102 St & 1 Ave,40.786995,-73.941648,3379.0,E 103 St & Lexington Ave,40.790305,-73.947558,21013,Subscriber,1969,Undisclosed

In [56]:
shape = combined_data.shape

In [57]:
shape

(2866241, 15)

In [58]:
combined_data.to_csv("Citibike_Data_Winter2019.csv", index=False)